apiVersion: v1
kind: Secret
metadata:
  name: staysphere-secret
type: Opaque
stringData:
  MONGO_URL: "mongodb://mongo-service:27017/realestateDB"
  FLIGHT_DB_URL: "mongodb://mongo-service:27017/flightDB"
  SECRET: "mysecretkey"
  PAYPAL_CLIENT_ID: "AesgvOw5DNre7zZh7KGOyuqLXeOFiPsqrXiKF89hKCDcJSbHpgcG82M6vRjOkudfPu98BFGa29gP7hWZ"
  PAYPAL_CLIENT_SECRET: "EOaw7joijsyOnLmyZx1up_5yUb4l1VMnc5PxkWu8aqdxsxaQ1nWdJCEIDba0nCv2O1-7JPXKK567BDgn"
  PAYPAL_BASE_URL: "https://api-m.sandbox.paypal.com"
  BASE_URL: "http://localhost:3000"